### ISSUE TITLE
Assume END:VCALENDAR at the end when missing

### ISSUE THREAD

**Issue by mtlg** [asciipip/mutt-ical#4]
I'm receiving broken ICS invites from Microsoft Teams that lack the ending 'END:VCALENDAR'. No comments...

This breaks the processing of the file, resulting in an exception.

I 'dirty fixed' this by synthesizing the missing END:VCALENDAR in cal.py, just to make it work (not suggeting this as a patch):

```--- a/cal.py	2023-12-11 11:40:32.992656593 +0100
+++ b/cal.py	2023-12-11 11:33:52.273658512 +0100
@@ -323,10 +323,15 @@
         """
         stack = []  # a stack of components
         comps = []
+        seen_end_vcal = False
         for line in Contentlines.from_ical(st):  # raw parsing
             if not line:
                 if seen_end_vcal:
                     continue
+                else:
+                    line = Contentlines.from_ical('END:VCALENDAR')[0]
+
+            seen_end_vcal = line == 'END:VCALENDAR'
 
             try:
                 name, params, vals = line.parts()
```

Is it possible to add a fix for such broken files?

**Comment by asciipip** [comment]
This is really a question for the [Python `icalendar` library](https://github.com/collective/icalendar/), since that's what handles the parsing and that's whose code you modified for your patch.

However:

 1. I doubt they'd want to add code to handle this sort of case, because an iCalendar file without `END:VCALENDAR` is well out of compliance with the specification and I'm not sure I'd want to trust an iCalendar file with obviously malformed data. (What if the file got truncated halfway through and is missing important events or event fields?) The real solution would be to fix the program generating malformed iCalendar files.
 2. This behavior was, in fact, regarded as a bug by Microsoft and was fixed. See, for example, the Microsoft Answers topic “[ICS files are missing end nodes](https://answers.microsoft.com/en-us/outlook_com/forum/all/ics-files-are-missing-end-nodes/fb2e1cc7-eed5-43e2-a62f-bebc653e119f)”.
